version: '3.8'
services:
  profile_:
    depends_on:
      - postgres_db
    build: 
      context: .
      dockerfile: Dockerfile
    image: idein:v1
    environment:
      - PORT=8020
    env_file:
      - ./.env
    ports:
      - "8001:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && sh /app/entrypoint.sh"

  postgres_db:
    image: postgres
    command: -p 5432
    env_file:
      - ./.env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

