# Generated by Django 4.1.5 on 2023-04-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='target_feature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
